version: 0.2

variables:
    APP_NAME: "bgconverter"
    
phases:
  install:
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - python manage.py makemigrations $APP_NAME
      - python manage.py migrate $APP_NAME
      - python manage.py collectstatic --no-input
      - python manage.py test

artifacts:
  type: zip
  files:
    - '**/*'
  base-directory: '.'
